TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
#DB += xxx.db
DB += MS_UI.db
DB += MS.db
DB += MS_TwoThetaStep.db
DB += MS_TwoThetaTemp.db
DB += MS_TwoThetaStepSlits.db
DB += MS_UI_settings.req
DB += MS_settings.req
DB += MS_TwoThetaStep_settings.req
DB += MS_TwoThetaTemp_settings.req
DB += MS_TwoThetaStepSlits_settings.req
DB += MS_Support.db
DB += MS_Support_settings.req

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

